# Generated by Django 5.2.4 on 2025-07-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('adventure', 'Adventure & Exploration'), ('historical', 'Historical & Cultural'), ('beach', 'Beach & Relaxation'), ('mountain', 'Mountain & Hiking'), ('camping', 'Camping & Outdoor'), ('city', 'City Tours & Urban'), ('food', 'Food & Culinary'), ('shopping', 'Shopping Trips'), ('nature', 'Nature & Wildlife'), ('sports', 'Sports & Activities')], default='city', max_length=50)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
