# Generated by Django 5.2.4 on 2025-07-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.CharField(choices=[('adventure', 'Adventure & Exploration'), ('historical', 'Historical & Cultural'), ('beach', 'Beach & Relaxation'), ('mountain', 'Mountain & Hiking'), ('camping', 'Camping & Outdoor'), ('city', 'City Tours & Urban'), ('nature', 'Nature & Wildlife')], default='city', max_length=50),
        ),
    ]
