# Generated by Django 5.2.4 on 2025-07-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_alter_comment_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspirationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('nature', 'Nature'), ('city', 'City')], max_length=50)),
            ],
        ),
    ]
