# Generated by Django 5.2.4 on 2025-07-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_inspirationvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InspirationVideo',
        ),
    ]
