# Generated by Django 5.2.4 on 2025-07-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_trip_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
