# Generated by Django 5.2.4 on 2025-07-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_alter_trip_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, '😡 Terrible Trip'), (2, '😐 Not Great'), (3, '😊 Nice Trip'), (4, '😍 Amazing Experience')]),
        ),
    ]
